### ISSUE TITLE
Bash Tab Completion

### ISSUE THREAD

**Issue by rylancates** [raxod502/pass-ln#2]
Hi there,

First of all - thank you so much for putting this together! This is exactly what I was looking for. I was redirected here from libera.chat in response to multiple urls per username/password.

Now, one thing that I'd love to see is bash tab completion to really round this excellent extension out :)

Thanks again and kudos!

**Comment by raxod502** [comment]
Ah, okay, based on this text

```
                # To add completion for an extension command define a function like this:
                # __password_store_extension_complete_<COMMAND>() {
                #     COMPREPLY+=($(compgen -W "-o --option" -- ${cur}))
                #     _pass_complete_entries 1
                # }
                #
                # and add the command to the $PASSWORD_STORE_EXTENSION_COMMANDS array
                if [[ " ${PASSWORD_STORE_EXTENSION_COMMANDS[*]} " == *" ${COMP_WORDS[1]} "* ]] && type "__password_store_extension_complete_${COMP_WORDS[1]}" &> /dev/null; then
                        "__password_store_extension_complete_${COMP_WORDS[1]}"
                fi
```

it looks like that should be possible - so, good suggestion, I can do that in the future bandwidth permitting, or will review a PR.

**Comment by raxod502** [comment]
Added with https://github.com/radian-software/pass-ln/pull/4. I am making a new release now.

**Comment by rylancates** [comment]
Thank you!
